package vista;

import Conexion.Conecta;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.devolverLibro;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ferto
 */
public class FRMDevolverLibro extends javax.swing.JInternalFrame {

    devolverLibro devolver = new devolverLibro();

    String zero = "0";

    Statement stmt;
    Conecta con;

    public FRMDevolverLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        TXTIdUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTIdLibro = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TXTNombrelibro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TXTFechap = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TXTFechaE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTObservacion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Devolver Libro");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(255, 153, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(240, 240, 240));
        jButton4.setText("Devolver");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 130, 40));

        jButton5.setBackground(new java.awt.Color(255, 153, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(240, 240, 240));
        jButton5.setText("Limpiar  ");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 120, 40));

        TXTIdUsuario.setBackground(new java.awt.Color(255, 255, 255));
        TXTIdUsuario.setForeground(new java.awt.Color(255, 153, 0));
        TXTIdUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        getContentPane().add(TXTIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Al devolver el libro pasara a  disponibles");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("ID Libro que tiene el usuario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, -1));

        TXTIdLibro.setBackground(new java.awt.Color(255, 255, 255));
        TXTIdLibro.setForeground(new java.awt.Color(255, 153, 0));
        TXTIdLibro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        TXTIdLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTIdLibroActionPerformed(evt);
            }
        });
        getContentPane().add(TXTIdLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 160, 30));

        jButton3.setBackground(new java.awt.Color(255, 153, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(240, 240, 240));
        jButton3.setText("   Buscar   ");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Identificacion Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Nombre Libro");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 100, -1));

        TXTNombrelibro.setBackground(new java.awt.Color(255, 255, 255));
        TXTNombrelibro.setForeground(new java.awt.Color(255, 153, 0));
        TXTNombrelibro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        TXTNombrelibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNombrelibroActionPerformed(evt);
            }
        });
        getContentPane().add(TXTNombrelibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 160, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("--------------------------------------------------------------------------------------");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 430, -1));

        TXTFechap.setBackground(new java.awt.Color(255, 255, 255));
        TXTFechap.setForeground(new java.awt.Color(255, 153, 0));
        TXTFechap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        getContentPane().add(TXTFechap, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("Fecha De Prestamo ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 130, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 153, 0));
        jLabel11.setText("Observacion al Devolver");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 150, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 0));
        jLabel12.setText("Fecha De Entrega ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 130, -1));

        TXTFechaE.setBackground(new java.awt.Color(255, 255, 255));
        TXTFechaE.setForeground(new java.awt.Color(255, 153, 0));
        TXTFechaE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        TXTFechaE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTFechaEActionPerformed(evt);
            }
        });
        getContentPane().add(TXTFechaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 160, 30));

        TXTObservacion.setBackground(new java.awt.Color(255, 255, 255));
        TXTObservacion.setColumns(20);
        TXTObservacion.setForeground(new java.awt.Color(255, 153, 0));
        TXTObservacion.setRows(5);
        TXTObservacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        jScrollPane1.setViewportView(TXTObservacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 330, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 440, 530));

        jLabel4.setFont(new java.awt.Font("Dialog", 2, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Devolver Un Libro");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 36, 310, 50));

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        obtenerLibro();
        devolver.seleccione();
        String comova = devolver.getComoVa();
        if (comova == "seleccionlisto") {
            devolver.editar1();
            comova = devolver.getComoVa();
            if (comova == "editar1listo") {
                devolver.editar2();
                comova = devolver.getComoVa();
                if (comova == "editar2listo") {
                    JOptionPane.showMessageDialog(this, "libro devuelto con exito ");
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(this, "error al devolber el libro ");
                }
            } else {
                JOptionPane.showMessageDialog(this, "error al devolber el libro ");
            }
        } else {
            JOptionPane.showMessageDialog(this, "error al seleccionar el libro o el usuario, no se devolvio ");
        }
        devolver.limpiar();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        this.TXTIdLibro.setText("");
        this.TXTNombrelibro.setText("");
        this.TXTIdUsuario.setText("");
        this.TXTFechap.setText("");
        this.TXTFechaE.setText("");
        this.TXTObservacion.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        obtenerLibro();
        devolver.seleccione();
        String as = devolver.getNombreLibro();
        String as1 = devolver.getFechaP();
        String as2 = devolver.getFechaE();
        TXTNombrelibro.setText(as);
        TXTFechap.setText(as1);
        TXTFechaE.setText(as2);
        if (TXTNombrelibro.getText() == null || TXTNombrelibro.getText() == "") {

            JOptionPane.showMessageDialog(this, "Error al buscar el libro prestado");

        }
        devolver.limpiar();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void TXTIdLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTIdLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTIdLibroActionPerformed

    private void TXTFechaEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTFechaEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTFechaEActionPerformed

    private void TXTNombrelibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNombrelibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNombrelibroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTFechaE;
    private javax.swing.JTextField TXTFechap;
    private javax.swing.JTextField TXTIdLibro;
    private javax.swing.JTextField TXTIdUsuario;
    private javax.swing.JTextField TXTNombrelibro;
    private javax.swing.JTextArea TXTObservacion;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private void obtenerLibro() {
        String a = TXTObservacion.getText();
        String b = TXTIdUsuario.getText();
        String c = TXTIdLibro.getText();
        devolver.setIdLibro(c);
        devolver.setIdUsuario(b);
        devolver.setObservacion(a);
    }

    private void limpiar() {
        this.TXTIdLibro.setText("");
        this.TXTNombrelibro.setText("");
        this.TXTIdUsuario.setText("");
        this.TXTFechap.setText("");
        this.TXTFechaE.setText("");
        this.TXTObservacion.setText("");
    }
}
