/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Conexion.conexionBD;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import modelo.genero;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ferto
 */
public class FRMgenero extends javax.swing.JInternalFrame {

    /**
     * Creates new form otros
     */
    public FRMgenero() {
        initComponents();
        genero gen = new genero();
            ArrayList<String> lista = new ArrayList<String>();
            lista = gen.busG();
            for(int i=0 ; i<lista.size() ; i++){
                combo.addItem(lista.get(i));
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Genero");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Genero:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 71, -1));

        jButton3.setBackground(new java.awt.Color(255, 153, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(240, 240, 240));
        jButton3.setText("Generar");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 90, 30));

        combo.setBackground(new java.awt.Color(255, 153, 0));
        combo.setForeground(new java.awt.Color(240, 240, 240));
        combo.setMaximumRowCount(6);
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        combo.setBorder(null);
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 190, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            
            String selC = this.combo.getSelectedItem().toString();
            if(selC == "Seleccione"){
                JOptionPane.showMessageDialog(this,"Seleccione Un Genero");
                return;
            }
            conexionBD con = new  conexionBD();
            JasperReport jrReporte =null;
            try{
                jrReporte = (JasperReport)JRLoader.loadObject( getClass().getClassLoader().getResource("reportes/buscarporgenero.jasper") );
                Map params = new HashMap();
                params.put("genero",selC);
                JasperPrint jpReporte = JasperFillManager.fillReport(jrReporte,params,con.getConnection());
                JasperViewer jReporteViewer = new JasperViewer (jpReporte,false);
                jReporteViewer.setVisible(true);
            }
            catch(Exception ex){
                System.out.println("jasper error ");
            } 
           

    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
