package vista;

import Conexion.Conecta;
import Conexion.fechA;
import static Conexion.fechA.fechaActual;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.prestarLibro;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ferto
 */
public class FRMPrestarlibro extends javax.swing.JInternalFrame {

    SimpleDateFormat dFormat = new SimpleDateFormat("dd/MM/YYYY");

    Statement stmt;
    Conecta con;
    prestarLibro presLibro = new prestarLibro();

    /**
     * Creates new form prestarlibro
     */
    public FRMPrestarlibro() {
        initComponents();
        //idb.setText(idloguin);
        this.TXTFechaDePrestamo.setText(fechaActual());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TXTIdLibro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXTIdUsuario = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTFechaDeEntrega = new com.toedter.calendar.JDateChooser();
        TXTIdBibliotecario = new javax.swing.JLabel();
        TXTFechaDePrestamo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Prestar Libro");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("ID Libro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 100, 30));

        TXTIdLibro.setBackground(new java.awt.Color(255, 255, 255));
        TXTIdLibro.setForeground(new java.awt.Color(255, 153, 0));
        TXTIdLibro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        getContentPane().add(TXTIdLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 150, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("ID Usuario ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 100, -1));

        TXTIdUsuario.setBackground(new java.awt.Color(255, 255, 255));
        TXTIdUsuario.setForeground(new java.awt.Color(255, 153, 0));
        TXTIdUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        getContentPane().add(TXTIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 150, 30));

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("Prestar ");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 130, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Fecha De Prestamo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Fecha De Entrega");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 120, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("ID Bibliotecario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 100, -1));

        TXTFechaDeEntrega.setBackground(new java.awt.Color(255, 153, 0));
        getContentPane().add(TXTFechaDeEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 150, 30));

        TXTIdBibliotecario.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        TXTIdBibliotecario.setForeground(new java.awt.Color(255, 153, 0));
        TXTIdBibliotecario.setText("id bibliotecario");
        getContentPane().add(TXTIdBibliotecario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 150, 30));

        TXTFechaDePrestamo.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        TXTFechaDePrestamo.setForeground(new java.awt.Color(255, 153, 0));
        TXTFechaDePrestamo.setText("fecha de prestamo");
        getContentPane().add(TXTFechaDePrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 150, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 410, 360));

        jLabel6.setFont(new java.awt.Font("Dialog", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prestar Un Libro");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 300, 50));

        jLabel4.setBackground(new java.awt.Color(255, 153, 0));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String a = TXTIdLibro.getText();
        String b = TXTIdUsuario.getText();
        try {
            String d = dFormat.format(TXTFechaDeEntrega.getDate());
        } catch (Exception ex) {

            System.out.println("Falta La Fecha De Entrega");
            JOptionPane.showMessageDialog(this, " Falta La Fecha De Entrega  ");
            return;
        }
        String d = dFormat.format(TXTFechaDeEntrega.getDate());
        String f = TXTIdBibliotecario.getText();

        if (a == null || a.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "No ingreso id libro ");
            return;
        }

        if (b == null || b.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, " No ingreso id usuario ");
            return;
        }

        if (d == null || d.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, " No ingreso fecha ");
            return;
        }

        if (f == null || f.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, " No ingreso id bibliotecario  ");
            return;
        }
        presLibro = obtenerLibro();
        presLibro.seleccionar();
        if (presLibro.getComoVa() == "seleccionbien") {
            presLibro.editar();
            if (presLibro.getComoVa() == "editarlisto") {
                presLibro.insertarEnPrestado();
                if (presLibro.getComoVa() == "insertarlisto") {
                    JOptionPane.showMessageDialog(this, "Prestado con exito");
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al prestar el libro ");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Error al prestar el libro ");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error al prestar el libro ");
        }
        presLibro.setComoVa("");
        presLibro.limpiar();


    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser TXTFechaDeEntrega;
    private javax.swing.JLabel TXTFechaDePrestamo;
    private javax.swing.JLabel TXTIdBibliotecario;
    private javax.swing.JTextField TXTIdLibro;
    private javax.swing.JTextField TXTIdUsuario;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    public void elidm(String asd) {
        TXTIdBibliotecario.setText(asd);

    }

    private prestarLibro obtenerLibro() {

        prestarLibro elPrestarLibro = new prestarLibro();
        elPrestarLibro.setIdlibroDoy(TXTIdLibro.getText());
        elPrestarLibro.setFechaDeEntrega(dFormat.format(TXTFechaDeEntrega.getDate()));
        elPrestarLibro.setFechaDePrestamo(TXTFechaDePrestamo.getText());
        elPrestarLibro.setIdusuario(TXTIdUsuario.getText());
        return elPrestarLibro;
    }

    private void limpiar() {
        TXTIdLibro.setText("");
        TXTIdUsuario.setText("");
        TXTFechaDeEntrega.setDate(null);
    }

}
