package vista;

import Conexion.Conecta;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.buscarLibrosDisponibles;
import modelo.buscarLibrosPrestados;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ferto
 */
public class FRMTablaDeLibrosPrestados extends javax.swing.JInternalFrame {

    public FRMTablaDeLibrosPrestados() {

        initComponents();
        buscarLibrosPrestadoss();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLLibros = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("libros Prestados");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tabla De Libros Prestados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 530, 70));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Actualizar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 80, 30));

        TBLLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TBLLibros.setSelectionBackground(new java.awt.Color(255, 153, 0));
        jScrollPane1.setViewportView(TBLLibros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 670, 360));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 750, 450));

        jLabel3.setBackground(new java.awt.Color(255, 153, 0));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        buscarLibrosPrestadoss();

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TBLLibros;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
   public void buscarLibrosPrestadoss() {
        buscarLibrosPrestados aLibros = new buscarLibrosPrestados();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID Libro");
        modelo.addColumn("Nombre Libro");
        modelo.addColumn("Identificacion De Usuario");
        modelo.addColumn("Fecha De Prestado");
        modelo.addColumn("Fecha De Entregado");
        TBLLibros.setModel(modelo);

        Iterator<buscarLibrosPrestados> iteratora = aLibros.buscarLibro();
        Object[] fila = new Object[TBLLibros.getColumnCount()];
        modelo.setRowCount(0);

        while (iteratora.hasNext()) {
            aLibros = iteratora.next();
            fila[0] = aLibros.getIdLibro();
            fila[1] = aLibros.getNombreLibro();
            fila[2] = aLibros.getIdUsuario();
            fila[3] = aLibros.getFechaDePrestamo();
            fila[4] = aLibros.getFechaDeEntregado();
            modelo.addRow(fila);

        }
        aLibros.limpiar();
    }
}
